[package]
name = "dd_count_total_panic"
version = "0.1.0"
edition = "2021"

[dependencies]
differential-dataflow = {git = "https://github.com/TimelyDataflow/differential-dataflow"}
timely = {git="https://github.com/TimelyDataflow/timely-dataflow"}
